### ISSUE TITLE
build failure against librabbitmq-c-0.6.0

### ISSUE THREAD

**Issue by travisghansen** [pdezwart/php-amqp#154] opened 2015-02-27 17:12 UTC
/home/thansen/Projects/arch-chaos/packages/php-amqp/src/amqp-1.6.0beta2/amqp_exchange.c:485:2: error: too few arguments to function ‘amqp_exchange_declare’
  amqp_exchange_declare(
  ^
In file included from /usr/include/amqp.h:740:0,
                 from /home/thansen/Projects/arch-chaos/packages/php-amqp/src/amqp-1.6.0beta2/amqp_exchange.c:42:
/usr/include/amqp_framing.h:798:11: note: declared here
 AMQP_CALL amqp_exchange_declare(amqp_connection_state_t state, amqp_channel_t channel, amqp_bytes_t exchange, amqp_bytes_t type, amqp_boolean_t passive, amqp_boolean_t durable, amqp_boolean_t auto_delete, amqp_boolean_t internal, amqp_table_t arguments);

**Comment by pinepain** [comment] 2015-02-27 17:35
Duplicate of https://github.com/pdezwart/php-amqp/issues/152.

Should be fixed in master branch by pull request https://github.com/pdezwart/php-amqp/pull/153.

**Comment by travisghansen** [comment] 2015-02-27 18:13
OK excellent.  I'll wait for a release!

**Comment by lstrojny** [comment] 2015-02-27 18:48
Closing as duplicate

**Closed by lstrojny** 2015-02-27 18:48 UTC
