### ISSUE TITLE
Please add method to close a channel ala RabbitMQ Java, Python and other clients

### ISSUE THREAD

**Issue by avinash240** [pdezwart/php-amqp#150] opened 2015-02-13 18:31 UTC
We currently generate a new channel for each call into a specific block of code in a long running process.  I'd expect the the destruction of the channel to reduce the "used_slot" attribute on the connection resource object.  However, it does not so we end up in a situation where we try to get a new channel and it fails, even though there is only one channel on the connection.  

Some sample code illustrating this issue:

        $conn = new AMQPConnection();
        $conn->setHost('localhost');
        $conn->setPort(5672);
        $conn->setVhost('/');
        $conn->setLogin('guest');
        $conn->setPassword('guest');
        $conn->connect();
        // Create a channel
        for($i=0; $i < 1000; $i++) {
            $ch = new AMQPChannel($conn);
            unset($ch);
            echo "COUNT: ", $i + 1, "\n";
        }

AMQPChannelException: Could not create channel. Connection has no open channel slots remaining.

**Comment by pinepain** [comment] 2015-02-13 18:59
Hey @avinash240 ! Can you provide more info on your issue, especially what php-amqp version you are using. If you are new at php-amqp troubleshooting, I would suggest you to look through [How to report a problem](https://github.com/pdezwart/php-amqp#how-to-report-a-problem) readme section.

P.S.: On 1.6.0beta2 I can't reproduce behavior you specified.

**Comment by avinash240** [comment] 2015-02-13 19:18
Sorry I should have read that, I'm using 1.4.0.  The max channel connection count is set at 254 1.4.0, so that code above errors out, in 1.6.0beta2 I see it's set at ~65k, so 1k wouldn't trigger it.

What I'm getting at, is if I create a channel object, **it increments the used_slots int inside the connection resource object**:

Line: 252 of amqp_connection_resource.c
```
    resource->used_slots++;
```

If that channel object goes out of scope and is garbage collected, the rabbitMQ server sees that that channel is no longer used, and knows that it's closed and removes the counter on it's end.  However, **the used_slots inside the connection resource object doesn't get decremented.**

In a long running process where people may want isolation and create a channel off a shared process connection object to do their work this eventually dies, even if there is only one channel open because the counter on the connection object never gets cleaned.

$ php -v
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

$ apt-cache policy librabbitmq-dev
librabbitmq-dev:
  Installed: 0.4.1-1

$ make -v
GNU Make 3.81
This program built for x86_64-pc-linux-gnu

**Comment by pinepain** [comment] 2015-02-13 19:42
Just try against latest fresh 1.6.0beta2 and install fresh rabbitmq-c (0.5.2 as of written). 

P.S. `used_slots` decremented in a few lines below, see line 265:

    		resource->used_slots--;

**Comment by avinash240** [comment] 2015-02-13 20:35
Yes, that's called in php_amqp_connection_resource_unregister_channel() which is only called when the connection is instantiated or disconnected.  It's not called on channel destruction.  On a side note I tried install 1.6.0beta2 from pecl and it error'd out on me.  It's complaining about a missing symbol which makes me believe the version of librabbitmq I have isn't up to date enough.

**Comment by pinepain** [comment] 2015-02-14 10:38
Yes, it required fresh `librabbitmq`. 

*Further text is about mainline php-amqp version. Note, that we do not backport features and fixes to older versions, we just release new one with fix or improvement. We do not offer pre-built packages not for php-amqp nor for librabbitmq*.

The rest you are talking about sounds strange for me. Channel closing done it it destructor (at least it should be and there is test `tests/amqpchannel_slots_usage.phpt` for that).

I have `channel_max=2` limit set in rabbitmq.conf (on the broker side), so I literally can't create more than 2 channels per connection. Then I run your code with listing how many used channel connection have an what is max allowed channels limit set:

```php
<?php

$conn = new AMQPConnection();
$conn->connect();

for($i=0; $i < 1000; $i++) {
    $ch = new AMQPChannel($conn);
    echo "COUNT: ", $i + 1, ' ', $conn->getUsedChannels(), ' ', $conn->getMaxChannels(), "\n";
    unset($ch);
}
```
COUNT: 1 1 2
COUNT: 2 1 2
COUNT: 3 1 2
COUNT: 4 1 2
...
COUNT: 996 1 2
COUNT: 997 1 2
COUNT: 998 1 2
COUNT: 999 1 2
COUNT: 1000 1 2
```
which gives me:

**Comment by avinash240** [comment] 2015-04-09 17:41
**$conn->getUsedChannels()** isn't in amqp 1.4.0, so I don't know what version you were running that tes with.  What is the current mainline version?  I just checked  out the latest from trunk and it does appear used_slots is being decremented on a channel going away:

    int php_amqp_connection_resource_unregister_channel(amqp_connection_resource *resource,   amqp_channel_t channel_id)
    {
    assert(resource != NULL);
    assert(resource->slots != NULL);
    assert(channel_id > 0 && channel_id <= PHP_AMQP_MAX_CHANNELS);

    if (resource->slots[channel_id] != 0) {
        resource->slots[channel_id] = 0;
        resource->used_slots--;
    }
    return SUCCESS;
    }

notice the old function from https://github.com/pdezwart/php-amqp/blob/v1.4.0/amqp_connection.c  not a single used_slot decrement to be found:

    void remove_channel_from_connection(amqp_connection_object *connection, amqp_channel_object *channel)
    {
	int slot;
	amqp_connection_resource *resource;

	channel->is_connected = '\0';

	/* Pull out the ring buffer for ease of use */
	resource = connection->connection_resource;

	/* Check that there is actually an open connection */
	if (!resource) {
		return;
	}

	/* Go through the slots looking for an opening */
	for (slot = 1; slot < DEFAULT_CHANNELS_PER_CONNECTION; slot++) {
		if (resource->slots[slot] == channel) {
			/* We found the channel, disconnect it: */
			amqp_channel_close(connection->connection_resource->connection_state, channel->channel_id, AMQP_REPLY_SUCCESS);

			/* Mark slot as used */
			resource->slots[slot] = (amqp_channel_object *) -1;

			return;
		}
	}
	return;
    }

yet on addition it incremented it
    int get_next_available_channel(amqp_connection_object *connection, amqp_channel_object *channel)
{
	int slot;

	/* Pull out the ring buffer for ease of use */
	amqp_connection_resource *resource = connection->connection_resource;

	/* Check if there are any open slots */
	if (resource->used_slots >= DEFAULT_CHANNELS_PER_CONNECTION) {
		return -1;
	}

	/* Go through the slots looking for an opening */
	for (slot = 1; slot < DEFAULT_CHANNELS_PER_CONNECTION; slot++) {
		if (resource->slots[slot] == 0) {
			/* Yay! we found a slot. Store the channel for later (disconnect needs to clean up connected channels) */
			resource->slots[slot] = channel;
			resource->used_slots++;

			/* Return the slot ID back so the channel can use it */
			return slot;
		}
	}

	return -1;
    }

**Comment by pinepain** [comment] 2015-04-09 22:31
Hi, thanks for paying attention to code quality! 

For now [v1.6.0beta2](https://github.com/pdezwart/php-amqp/tree/v1.6.0beta2) is latest tagged version, which still in beta (btw, all GA available releases are shown on https://pecl.php.net/package/amqp, but you can also look for fresh tags in github repo too).

As to decrementing, in earlier versions there was a lot of code that didn't work properly with AMQP protocol, incorrectly interpreted server errors and so, so channels was prohibited for reuse. Now that gone, so we can still reuse channel slots again.

**Comment by pinepain** [comment] 2015-11-05 17:23
@lstrojny, propose to close this.

**Closed** 2015-11-10 12:27 UTC
Labels: feedback-needed
