### ISSUE TITLE
Call "consume" method inside another "consume"

### ISSUE THREAD

**Issue by dakulov** [pdezwart/php-amqp#237] opened 2016-07-06 17:00 UTC
When I trying to call "consume" method inside another "consume",  
then handlers entangling for different queues.

For example:

``` php
<?php

$connection = new \AMQPConnection([
    "host" => "192.168.2.101",
    "port" =>  "5673",
    "login" => "user",
    "password" => "user"
]);

$connection->connect();

$channel1 = new \AMQPChannel($connection);

$ex1 = new AMQPExchange($channel1);
$ex1->setName('ex1');
$ex1->setType(AMQP_EX_TYPE_FANOUT);
$ex1->declareExchange();

$q1 = new AMQPQueue($channel1);
$q1->setName('q1');
$q1->setFlags(AMQP_DURABLE);
$q1->declareQueue();
$q1->bind('ex1');

$i = 0;
while ($i < 4) {
    $ex1->publish('{"message": "ping"}');
    $i++;
}

$q1->consume(function (\AMQPEnvelope $message, \AMQPQueue $queue) use ($connection) {

    $queue->ack($message->getDeliveryTag());
    printf("1: %s [%s]\n", $message->getExchangeName(), $message->getBody());

    $channel2 = new \AMQPChannel($connection);

    $ex2 = new AMQPExchange($channel2);
    $ex2->setName('ex2');
    $ex2->setType(AMQP_EX_TYPE_FANOUT);
    $ex2->declareExchange();

    $q2 = new AMQPQueue($channel2);
    $q2->setName('q2');
    $q2->setFlags(AMQP_DURABLE);
    $q2->declareQueue();
    $q2->bind('ex2');

    $q2->consume(function (\AMQPEnvelope $message, \AMQPQueue $queue) {
        printf("2: %s [%s]\n", $message->getExchangeName(), $message->getBody());
        $queue->ack($message->getDeliveryTag());
    });

});
```

expected output:

```
1: ex1 [{"message": "ping"}]
```

actual:

```
root@3ffd5ec8688f:/app/bin# php weird.php 
1: ex1 [{"message": "ping"}]
2: ex1 [{"message": "ping"}]
2: ex1 [{"message": "ping"}]
2: ex1 [{"message": "ping"}]
PHP Fatal error:  Uncaught exception 'AMQPException' with message 'Library error: unexpected protocol state' in /app/bin/weird.php:52
Stack trace:
#0 /app/bin/weird.php(52): AMQPQueue->consume(Object(Closure))
#1 [internal function]: {closure}(Object(AMQPEnvelope), Object(AMQPQueue))
#2 /app/bin/weird.php(54): AMQPQueue->consume(Object(Closure))
#3 {main}
  thrown in /app/bin/weird.php on line 52
```

Question: Is this normal behaviour or not?

php:

```
root@3ffd5ec8688f:/app/bin# php --version
PHP 5.5.35-1+donate.sury.org~trusty+4 (cli) (built: May 12 2016 14:03:14) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

```

extention:

```
Version => 1.7.0
Revision => release
Compiled => May 16 2016 @ 19:30:29
AMQP protocol version => 0-9-1
librabbitmq version => 0.7.1
```

**Comment by pinepain** [comment] 2016-07-06 22:05
Hi, thanks for the report! This script segfaults (on my machine) which is not an expected behavior for sure.

As to your script and php-amqp extension: we use `amqp_consume_message` from rabbitmq-c in `AMQPQueue::consume()` under the hood, which works a bit different from what user would expect in our case: it waits for any messages on a connection, not a channel. So nested calls to `AMQPQueue::consume()` considered weird within the same connection. I guess there are no easy way to fix this for now. We may except explicitly ban nested calls to `AMQPQueue::consume()` within the same connection to prevent false expectations. More proper fix will be to actually listen on a specific channel only.

**Comment by dakulov** [comment] 2016-07-07 08:08
Thanks you for the quick reply!

Should I wait for a good solution to this problem (listen on a specific channel only)?
Am I not mistaken that problem in amqp_consume_message (rabbitmq-c), not in php-extention?
Perhaps I need to contact rabbitmq-c developers?

**Comment by pinepain** [comment] 2016-07-07 08:31
As a workaround you may open second connection and do nested consume within it.

>  Am I not mistaken that problem in amqp_consume_message (rabbitmq-c), not in php-extention?
All projects that use `amqp_consume_message()` from rabbitmq-c in the same manner will have such problem. [php-amqplib](https://github.com/php-amqplib/php-amqplib) php library is fully implemented in php itself, so it should behaves different, but I haven't give it a try yet.

Let's ping @alanxz to see what he can clarify about whole this problem.

**Comment by alanxz** [comment] 2016-07-10 03:49
`amqp_connection_state_t` objects are not thread-safe. Using a single object from multiple threads without synchronization will result in undefined behavior, without looking at what php-amqp is doing in this is my guess.

**Comment by pinepain** [comment] 2016-07-10 10:35
@alanxz we don't use threads in this case. The code itself is `AMQPQueue::consume()` method  - https://github.com/pdezwart/php-amqp/blob/master/amqp_queue.c#L502.

The problem is that it calls `amqp_consume_message()` - https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp_consumer.c#L143 which listens for incoming message on a connection globally, and in our case it should listen only specific channel. Are there any way to to this with current rabbitmq-c API? From what I see it's not and the closest way to implement `amqp_consume_message_on_channel()` is to kinda copy-paste current `amqp_consume_message()` code and replace `amqp_simple_wait_frame_noblock()` method call on https://github.com/alanxz/rabbitmq-c/blob/master/librabbitmq/amqp_consumer.c#L154 with `amqp_simple_wait_frame_on_channel()`, right?

**Comment by alanxz** [comment] 2016-07-10 20:42
My recommendation is to use `amqp_consume_message()`, and store message that aren't on the channel you care about somewhere until they're ready to be consumed.

> Are there any way to to this with current rabbitmq-c API? 

Given the current public API, its possible, but not easy.  The way you might do it is to use `amqp_simple_wait_frame()` to read frames until you get a basic.deliver method on the channel you care about, putting aside frames you don't care about (e.g., messages on other channels). The difficult part is that then you have to keep track of the frames you read and don't use right away, which means in order to make this a general solution, you end up having to re-implement a lot of the rabbitmq-c API using only `amqp_simple_wait_frame()`. (This is what [alanxz/SimpleAmqpClient](https://github.com/alanxz/SimpleAmqpClient) does). I don't recommend doing this.

Getting `amqp_consume_message()` to consume on a per-channel basis would require making `amqp_simple_wait_frame_on_channel()` deal with timeouts correctly (which is part of the reason its not a public API).  My concern with making an `amqp_consume_message_on_channel()` API, is that if you have 2 active consumers on different channels, and only ever read the messages on one channel, this has the potential for unbounded memory growth as the `amqp_connection_state_t` object needs to keep all of the un-read messages, this is the other reason that `amqp_simple_wait_frame_on_channel()` isn't a public function. Having only an `amqp_consume_message()` API forces users of the library to deal with the memory growth issue in an appropriate way.

**Comment by pinepain** [comment] 2016-07-11 06:38
Thanks for clarification, it's something what I expected. I guess at this time we'll just may ban multiple channels consume at the same time within a single connection. As it hard and potentially break BC, it's better than having non-working functionality. And thanks for highlight about [alanxz/SimpleAmqpClient](https://github.com/alanxz/SimpleAmqpClient), I guess it can be a base for the next php-amqp major version.

**Comment by alanxz** [comment] 2016-07-13 22:04
I would look at what alanxz/SimpleAmqpClient offers carefully, it presents a rather opinionated interface that may not be what you're looking for.

**Comment by pinepain** [comment] 2017-06-10 19:00
@dakulov Hi, sorry for taking it so long. In #282 and #284 we finally passes proper queue to consumer callback. Unfortunately, not much to do in advance about original issue about consuming on exact channel: as Alan mentioned, at the moment it's not a something which is easily achievable from internals, neither how AMQP protocol works. The best guess is to handle envelopes by yourself: with proper queue (and enveloper consumer tag) it should do the job.

**Comment by lstrojny** [comment] 2017-06-12 13:10
Closing this for now

**Closed by lstrojny** 2017-06-12 13:10 UTC

**Comment by dakulov** [comment] 2017-06-13 12:19
@pinepain Thank you very much!
